name: check
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: tj-actions/changed-files@v35
        id: files
        with:
          files: streams/cn.m3u
      - uses: actions/setup-node@v3
        if: ${{ !env.ACT && steps.files.outputs.any_changed == 'true' }}
        with:
          node-version: 18
          cache: 'npm'
      - name: install dependencies
        if: steps.files.outputs.any_changed == 'true'
        run: npm install
      - name: validate
        if: steps.files.outputs.any_changed == 'true'
        run: |
           curl https://iyuu.cn/IYUU19280Te2bb892e042846d10e07d6eca3a43a5aff248584.send?text=IPTV+CHANGED&desp=iptvchanged&u=u&p=p
